### ISSUE TITLE
PRs stacking up

### ISSUE THREAD

**Issue by lucasgonze** [PlaintextGroup/oss-virtual-incubator#31]
**Describe the bug**

The pull request queue has items from five months ago. This is problematic for all sorts of reasons.

**Expected behavior**

Most proposal PRs could be merged within a day or so.

**Comment by epicfaace** [comment]
Hi! I think https://github.com/PlaintextGroup/oss-virtual-incubator/pull/4 is still awaiting some changes by the author, but I'm happy to merge it for now.
