### ISSUE TITLE
Typeform inaccessible

### ISSUE THREAD

**Issue by brainwane** [PlaintextGroup/oss-virtual-incubator#47]
**Describe the bug**
The proposal form is not accessible at the link provided in the README.

**To Reproduce**
1. Go to the `README`
2. Click on the link in "If you'd rather just use a form, [fill out this form](https://97oibfwziii.typeform.com/to/b60y2IZa)."

The page at that link says, "Sorry, you can't access this typeform until its creator says so."

**Expected behavior**
A form appears that the user can fill out.

**Comment by epicfaace** [comment]
We no longer are able to use typeform. Will need to switch to a google form.
