### ISSUE TITLE
Suggest likely timelines for consideration, approval, and funding

### ISSUE THREAD

**Issue by brainwane** [PlaintextGroup/oss-virtual-incubator#7]
Thank you for setting up this opportunity! I've just learned about it and I'd like to know a little more about likely timelines for consideration and approval and funding, so I can plan ahead. For example, are you planning on reviewing the proposals generally within a week of submission? Or: If you approve someone for funding and support, do you anticipate you would be able to start providing the policy help sooner but the funding might have to wait till the next quarter? 

A note in your README summarizing what applicants should expect would be great. Thanks!

**Comment by epicfaace** [comment]
@brainwane Thanks for the suggestion! We originally launched this repo as an experiment to see what we would get. Now that we've gotten a couple of proposals in, we have a better idea of what our review process will be, and we'll be updating the README soon to add this information in.
